### PR TITLE
[RHPAM-3689] Add JBPM Cluster jar in Kieserver image

### PR DESCRIPTION
**Pull request by desmax74**
See: https://issues.redhat.com/browse/RHPAM-3689
Signed-off-by: desmax74 <mdessi@redhat.com>

### CODE REVIEW

**Comment by desmax74** [comment]
@spolti

**Comment by spolti** [comment]
Seems that some needed changes are missing.

**Comment by desmax74** [comment]
@spolti which changes are needed ?

**Comment by spolti** [comment]
the description does not mention that..
you have updated only the tests, and about the part that actually updates the yaml files?

**Comment by spolti** [comment]
please open a KIECLOUD jira for the changes need to automatically update the clustering the emitter jars.
it can be done later.

**Comment by desmax74** [comment]
@spolti fixed

**Pull request closed without merging**
